/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/small-avatar.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useCharacterAnimations } from '../contexts/CharecterAnimationContext'

const  Avatar=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/small-avatar.glb')
  const { actions ,names} = useAnimations(animations, group)
  const { setAnimations, animationIndex } = useCharacterAnimations();



useEffect(()=>{
setAnimations(names)
},[names])
  useEffect(()=>{
actions[names[animationIndex]].reset().fadeIn(0.5).play()
return ()=>{
 actions[names[animationIndex]].fadeOut(0.5)
}

  },[animationIndex])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="position_Bison" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.Hips_bk} />
          <group name="black_Bison">
            <skinnedMesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.bison_texture} skeleton={nodes.Mesh.skeleton} castShadow />
            <skinnedMesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.bison_metallic} skeleton={nodes.Mesh_1.skeleton} castShadow />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Avatar

useGLTF.preload('./models/small-avatar.glb')
