/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/WOMEN.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useCharacterAnimations } from '../contexts/CharecterAnimationContext'
const Women=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/WOMEN.glb')
  const { actions, names} = useAnimations(animations, group)

  const { setAnimations, animationIndex } = useCharacterAnimations();



 
useEffect(()=>{
setAnimations(names)
},[names])

useEffect(()=>{
  actions[names[animationIndex]].reset().fadeIn(0.5).play()
  return ()=>{
   actions[names[animationIndex]].fadeOut(0.5)
  }
},[animationIndex])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Mdea_mesh">
            <skinnedMesh name="Mdea_mesh_1" geometry={nodes.Mdea_mesh_1.geometry} material={materials.Mdea_MAT} skeleton={nodes.Mdea_mesh_1.skeleton} castShadow />
            <skinnedMesh name="Mdea_mesh_2" geometry={nodes.Mdea_mesh_2.geometry} material={materials.Mdea_MAT_} skeleton={nodes.Mdea_mesh_2.skeleton} castShadow />
          </group>
        </group>
      </group>
    </group>
  )
}
export default Women 
useGLTF.preload('./models/WOMEN.glb')
